
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
#     sh "flutter clean"
#     sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:197603519265:android:4ce0fccaa217987abf2c60",
        firebase_cli_token: "1//03bufWh9eMt7yCgYIARAAGAMSNwF-L9Ire2dUALUXvLZnbnc6zDobrgYUuF_KggFG-xKBJiqnkN9fsu9Uwy8DHOxk32Ws_FO-vnM",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "ahmd.elgharib8899@gmail.com",
        release_notes: "First Fastlane Firebase Distribution"
      )
  end
end
